@startuml
left to right direction
skinparam packageStyle rectangle

actor "Configuratore" as Admin
actor "Fruitore" as User

rectangle "Applicazione Proposte - Versione 3" {
    package "V2 (Configuratore)" {
      usecase "Login / Cambio Password" as UC1
      usecase "Gestisci Categorie e Campi" as UC2
      usecase "Crea e Pubblica Proposta" as UC3
      usecase "Visualizza Bacheca" as UC4
    }

    package "V3 (Fruitore)" {
      usecase "Registrazione" as UC8
      usecase "Visualizza Bacheca" as UC9
      usecase "Iscrizione a Proposta Aperta" as UC10
      usecase "Ritiro Iscrizione" as UC11
      usecase "Visualizza Notifiche" as UC12
      usecase "Cancella Notifica" as UC13
    }
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4

User --> UC8
User --> UC9
User --> UC10
User --> UC11
User --> UC12
User --> UC13

UC13 .> UC12 : <<include>>

@enduml
