@startuml
left to right direction
skinparam packageStyle rectangle

actor "Configuratore" as Admin
actor "Fruitore" as User

rectangle "Applicazione Proposte - Versione 4" {
    package "V3 (Configuratore)" {
      usecase "Gestisci Categorie e Campi" as UC_A
      usecase "Crea e Pubblica Proposta" as UC_B
      usecase "Visualizza Bacheca" as UC_C
    }

    package "V3 (Fruitore)" {
      usecase "Iscrizione a Proposta" as UC_D
      usecase "Visualizza Notifiche" as UC_E
    }

    package "V4" {
      usecase "Ritira Proposta\n(Aperta o Confermata)" as UC1
      usecase "Disiscrizione con\ncontrollo scadenza" as UC2
      usecase "Notifica Automatica Ritiro\na tutti gli iscritti" as UC5
      usecase "Storico iscritti\nconservato" as UC4
    }
}

Admin --> UC_A
Admin --> UC_B
Admin --> UC_C
Admin --> UC1

User --> UC_D
User --> UC_E
User --> UC2

UC1 .> UC5 : <<include>>
UC1 .> UC4 : <<include>>

@enduml
